webserver/homeapp/urls.py
from django.urls import path, include
from . import views

app_name = 'homeapp'
urlpatterns = [
    path('', views.home_view, name="home_url"),
    path('ethernet/', views.ethernet_view, name="ethernet_url"),
    path('sound/', views.sound_view, name="sound_url"),
    path('about/', views.about_view, name="about_url"),
]

webserver/webserver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeapp.urls'))
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/homeapp/models.py
from django.db import models

# Create your models here.

webserver/homeapp/views.py
from django.shortcuts import render
from subprocess import *

# Create your views here.
def home_view(request):
    return render(request, "home.html")

def ethernet_view(request):
    if request.method == 'POST':
        dev_name = request.POST['device_name']
        speed = request.POST['speed']
        duplex = request.POST['duplex']
        process = run(['ethtool', '-s', dev_name, 'speed', speed, 'duplex', duplex], stdout=PIPE)
    script = '/home/user/tk-sysprog-scripts/webserver/homeapp/get_ethernet_devices.sh'
    get_dev_process = run(['bash', script], stdout=PIPE)
    device_info_raw = get_dev_process.stdout.decode('utf-8').split('\n')
    devices = []
    for device in device_info_raw:
        if(device != ''):
            device_info = device.split(';')
            print(device_info)
            dev_name = device_info[0]
            addr = device_info[1]
            driver = device_info[2]
            status = device_info[3]
            alm = device_info[4]
            devices.append({'dev_name':dev_name, 'addr':addr, 'driver':driver, 'status':status, 'alm':alm})
    return render(request, "ethernet.html", {'devices':devices})

def sound_view(request):
    if request.method == 'POST':
        if 'play_button' in request.POST:
            process1 = run(['aplay', '/usr/share/sounds/alsa/Front_Center.wav'], stdout=PIPE)

        if 'volume_level' in request.POST:
            try:
                volume = int(request.POST['volume_level'])
            except TypeError:
                volume = 0

            if volume > 0:
                process2 = run(['amixer', '-q', 'sset', 'Master', f'{volume}%+'])
            elif volume < 0:
                volume = abs(volume)
                process2 = run(['amixer', '-q', 'sset', 'Master', f'{volume}%-'])
    return render(request, "sound.html")

def about_view(request):
    return render(request, "about-us.html")

webserver/homeapp/templates/about-us.html
{% extends 'base.html' %}
{% load static %}
{% block header %} {% endblock %}

{% block content %}
<div class="container mx-auto">
    <div class="container-body-author">
        <h3>Authors</h3>
        <p>System Programming A - 2020</p>
        <p>Kelompok jagung_manis</p>
        <p>1. Evando Wihalim - 1806205445</p>
        <p>2. Jovi Handono Hutama - 1806205161</p>
        <p>3. Michael Susanto - 1806205653</p>
    </div>
</div>
{% endblock %}

webserver/homeapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block header %}{% endblock %}
    <title>Jagung Manis</title>
</head>
<body>
    <div class="container-navbar">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'homeapp:home_url' %}">jagung_manis</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
              {% with url_name=request.resolver_match.url_name %}
                <li class="nav-item {% if url_name == 'home_url' %} active {% endif %} ">
                  <a class="nav-link" href="{% url 'homeapp:home_url' %}">Home</a>
                </li>
                <li class="nav-item {% if url_name == 'ethernet_url' %} active {% endif %} ">
                  <a class="nav-link" href="{% url 'homeapp:ethernet_url' %}">Ethernet</a>
                </li>
                <li class="nav-item {% if url_name == 'sound_url' %} active {% endif %} ">
                  <a class="nav-link" href="{% url 'homeapp:sound_url' %}">Sound</a>
                </li>
                <li class="nav-item {% if url_name == 'about_url' %} active {% endif %} ">
                  <a class="nav-link" href="{% url 'homeapp:about_url' %}">About Us</a>
                </li>
              {% endwith %}
              </ul>
            </div>
          </nav>
    </div>

    {% block content %}{% endblock content %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

webserver/homeapp/templates/ethernet.html
{% extends 'base.html' %}
{% load static %}
{% block header %}{% endblock %}

{% block content %}
<div class="container mx-auto">
    <h1>Configure Ethernet</h1>
</div>
<div class="container mx-auto">
    <div class="container-body-main">
        <h3>Your Network Devices & Drivers</h3>
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Device</th>
                <th scope="col">Address</th>
                <th scope="col">Driver</th>
                <th scope="col">Status</th>
                <th scope="col">Advertised Link Modes</th>
              </tr>
            </thead>
            <tbody>
	      {% if devices %}
	      {% for dev in devices %}
              <tr>
		      <td>{{ dev.dev_name }}</td>
		      <td>{{ dev.addr }}</td>
		      <td>{{ dev.driver }}</td>
		      <td>{{ dev.status }}</td>
		      <td>{{ dev.alm }}</td>
              </tr>
	      {% endfor %}
	      {% endif %}
	    </tbody>
        </table>

        <form class="capacity-form" action="{% url 'homeapp:ethernet_url' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="device_name">Device Name</label>
                <input type="text" class="form-control" id="device_name" placeholder="Enter device name" name="device_name" required>
            </div>
            <div class="form-group">
                <p>Speed (Mbps)</p>
                <label class="radio-inline"><input type="radio" name="speed" value="10" required>10</label>
                <label class="radio-inline"><input type="radio" name="speed" value="100">100</label>
                <label class="radio-inline"><input type="radio" name="speed" value="1000">1000</label>
            </div>
            <div class="form-group">
                <p>Duplex</p>
                <label class="radio-inline"><input type="radio" name="duplex" value="half" required>Half</label>
                <label class="radio-inline"><input type="radio" name="duplex" value="full">Full</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
</div>
{% endblock %}

webserver/homeapp/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block header %} {% endblock %}

{% block content %}
<div class="container mx-auto">
    <h1>Welcome to Jagung Manis Driver</h1>
</div>
<div class="container mx-auto">
    <div class="container">
        <p>Welcome!</p>
        <p>This web app will be run inside a virtual machine, 
            to serve as User Interface for managing network driver e1000 and PCI soundcard driver. 
            This web app can change speed and duplex of an ethernet device with ethtool 
            (tool to modify ethernet driver), and adjust audio system volume from amixer 
            (tool to modify soundcard driver)
        </p>
    </div>
</div>
{% endblock %}

webserver/homeapp/templates/sound.html
{% extends 'base.html' %}
{% load static %}
{% block header %}{% endblock %}

{% block content %}
<div class="container mx-auto">
    <h1>Configure Sound</h1>
</div>
<div class="container mx-auto">
    <div class="container-body-main">
        <h3>Sample sound</h3>
	<form action="{% url 'homeapp:sound_url' %}" method="POST">
	{% csrf_token %}
            <button type="submit" class="btn btn-outline-primary" value="play" name="play_button">Play</button>
	</form>        

        <h3>Configure volume</h3>
        <form action="{% url 'homeapp:sound_url' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="volume_level">Volume (level)</label>
                <input type="number" class="form-control" id="volume_level" name="volume_level" placeholder="Enter volume level" required min="-100" max="100">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
    </div>
</div>
{% endblock %}